version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - flask-app
